"""Bibliothèque d'idées de produits à revenu récurrent construits sur Jev.
Chaque idée est notée par Jev à chaque passage (critères ci-dessous) et croisée avec la traction
de sa niche sur X. `n` = clé de niche (niches.py) ou None si personne n'en parle encore."""

# (clé, niche, titre en, titre fr, pitch en, pitch fr, acheteur en, acheteur fr, prix)
_IDEAS = [
    ("pr_guard", "code_review", "PR risk checker", "Contrôle de risque des PR",
     "GitHub App asking 15 typed questions on every diff (secrets, auth, deleted tests, breaking API) and blocking risky merges.",
     "GitHub App qui pose 15 questions typées sur chaque diff (secrets, auth, tests supprimés, API cassée) et bloque les merges risqués.",
     "Engineering teams", "Équipes tech", "$29/repo/mo"),
    ("agent_permissions", "agent_safety", "Natural-language agent permissions", "Permissions d'agents en langage naturel",
     "Drop-in policy layer for Claude Code, Codex and opencode: write rules in plain words, Jev approves or blocks each command in 200 ms.",
     "Couche de règles pour Claude Code, Codex, opencode : règles en langage courant, Jev valide ou bloque chaque commande en 200 ms.",
     "Teams using coding agents", "Équipes qui utilisent des agents de code", "$10/seat/mo"),
    ("context_pruner", "context_compaction", "Instant context pruner", "Élagueur de contexte instantané",
     "Plugin that drops stale tool calls from agent sessions in one second, cutting token bills and keeping agents sharp.",
     "Plugin qui retire en 1 s les appels d'outils périmés des sessions d'agents : factures de tokens réduites, agents plus précis.",
     "Heavy agent users", "Gros utilisateurs d'agents", "$9/mo"),
    ("model_router", "tool_routing", "Cheapest-capable model router", "Routeur vers le modèle le moins cher",
     "Proxy that asks Jev how hard each request is and sends it to the cheapest model that can handle it; bills a share of savings.",
     "Proxy qui demande à Jev la difficulté de chaque requête et l'envoie au modèle le moins cher capable ; facture une part des économies.",
     "AI startups", "Startups IA", "20% of savings"),
    ("skill_picker", "tool_routing", "Agent skill & tool picker", "Sélecteur de skills et d'outils",
     "Ranks hundreds of tools or skills for each agent turn so only the right one enters the prompt.",
     "Classe des centaines d'outils ou de skills à chaque tour d'agent pour n'injecter que le bon dans le prompt.",
     "Agent framework builders", "Créateurs de frameworks d'agents", "$49/mo"),
    ("fast_browser_api", "browser_automation", "Fast browser automation API", "API d'automatisation web rapide",
     "Hosted browser agent where Jev picks every click: bookings, forms, scraping at a fraction of LLM-agent cost.",
     "Agent navigateur hébergé où Jev choisit chaque clic : réservations, formulaires, scraping pour une fraction du coût d'un agent LLM.",
     "Ops & growth teams", "Équipes ops et growth", "usage-based"),
    ("voice_browser", "voice_control", "Voice-driven browser", "Navigateur à la voix",
     "Speak and the browser acts in 300 ms: accessibility and hands-free productivity.",
     "Tu parles, le navigateur agit en 300 ms : accessibilité et productivité mains libres.",
     "Accessibility users, power users", "Accessibilité, utilisateurs avancés", "$8/mo"),
    ("release_breaker", "qa_testing", "Release breaker", "Casseur de releases",
     "Swarm of Jev-driven testers that attack every deploy and report regressions before users do.",
     "Essaim de testeurs pilotés par Jev qui attaquent chaque déploiement et signalent les régressions avant les utilisateurs.",
     "SaaS teams", "Équipes SaaS", "$99/mo"),
    ("sheet_column", "data_labeling", "AI column for spreadsheets", "Colonne IA pour tableurs",
     "Google Sheets / Excel add-on: type a header like 'Urgency' and every row gets labeled in 100 ms.",
     "Add-on Google Sheets / Excel : tu écris un en-tête comme « Urgence » et chaque ligne est notée en 100 ms.",
     "Analysts, ops", "Analystes, ops", "$12/mo"),
    ("sql_classify", "data_labeling", "SQL classify() for warehouses", "Fonction SQL classify() pour entrepôts",
     "A classify() function for DuckDB, Postgres or BigQuery that labels millions of rows at pennies.",
     "Une fonction classify() pour DuckDB, Postgres ou BigQuery qui étiquette des millions de lignes pour quelques centimes.",
     "Data teams", "Équipes data", "usage-based"),
    ("inbox_triage", "email_triage", "Inbox autopilot", "Pilote automatique de boîte mail",
     "Sorts, prioritizes and labels every incoming email in real time; learns your categories.",
     "Trie, priorise et étiquette chaque email entrant en temps réel ; apprend tes catégories.",
     "Founders, busy professionals", "Fondateurs, pros débordés", "$6/mo"),
    ("ticket_router", "support_routing", "Ticket router for help desks", "Routeur de tickets pour help desk",
     "Zendesk / Intercom / Freshdesk app that tags urgency, topic and team for each ticket instantly.",
     "App Zendesk / Intercom / Freshdesk qui attribue urgence, sujet et équipe à chaque ticket instantanément.",
     "Support teams", "Équipes support", "$49/mo"),
    ("churn_signals", "support_routing", "Churn signal detector", "Détecteur de signaux de churn",
     "Reads support messages and product feedback, flags customers about to cancel with a probability.",
     "Lit les messages support et les retours produit, signale les clients sur le point de partir avec une probabilité.",
     "SaaS founders", "Fondateurs SaaS", "$79/mo"),
    ("lead_scorer", "lead_scoring", "Lead & message scorer", "Scoring de leads et de messages",
     "CRM plugin scoring every lead's buying intent and every outreach message before it is sent.",
     "Plugin CRM qui note l'intention d'achat de chaque lead et chaque message de prospection avant l'envoi.",
     "Sales teams, agencies", "Équipes commerciales, agences", "$39/seat/mo"),
    ("intent_monitor", "lead_scoring", "Buying-intent social monitor", "Veille d'intention d'achat",
     "Watches X, Reddit and forums for posts asking for a product like yours and alerts you within minutes.",
     "Surveille X, Reddit et les forums à la recherche de posts qui cherchent un produit comme le tien et t'alerte en quelques minutes.",
     "Indie founders", "Fondateurs indés", "$19/mo"),
    ("ad_spy", "ad_intelligence", "Competitor ad breakdown", "Décryptage des pubs concurrentes",
     "Weekly scan of competitors' live ads: hook, offer, CTA, awareness stage, landing mismatch.",
     "Scan hebdomadaire des pubs actives des concurrents : accroche, offre, CTA, niveau de conscience, incohérence de landing.",
     "DTC brands, media buyers", "Marques DTC, media buyers", "$99/mo"),
    ("creative_prescore", "ad_intelligence", "Ad creative pre-scorer", "Pré-score de créas publicitaires",
     "Scores ad copy and scripts before launch against patterns of winning ads.",
     "Note les textes et scripts de pubs avant lancement selon les schémas des pubs gagnantes.",
     "Performance marketers", "Marketeurs de performance", "$49/mo"),
    ("viral_score", "content_virality", "Post virality coach", "Coach de viralité",
     "Scores a post with 60 typed questions, shows what helps and hurts, loops until the score peaks.",
     "Note un post avec 60 questions typées, montre ce qui aide et ce qui freine, boucle jusqu'au score maximal.",
     "Creators", "Créateurs", "$12/mo"),
    ("youtube_title", "content_virality", "YouTube title & thumbnail tester", "Testeur de titres YouTube",
     "Predicts which title and thumbnail description will pull the most clicks for a channel.",
     "Prédit quel titre et quelle miniature attireront le plus de clics pour une chaîne.",
     "YouTubers", "YouTubeurs", "$15/mo"),
    ("newsjack", "newsjacking_pr", "Daily newsjacking brief", "Brief quotidien de newsjacking",
     "Every morning: which stories each brand should jump on, with the angle.",
     "Chaque matin : quelles actus chaque marque doit reprendre, avec l'angle.",
     "Brands, PR agencies", "Marques, agences RP", "$149/mo"),
    ("feed_cleaner", "moderation", "Feed cleaner extension", "Extension de nettoyage de fil",
     "Hides rage bait, engagement farming, crypto spam and politics from X, LinkedIn and Reddit.",
     "Masque rage bait, farming d'engagement, spam crypto et politique sur X, LinkedIn et Reddit.",
     "Everyday users", "Grand public", "$3/mo"),
    ("community_mod", "moderation", "Community auto-moderator", "Automodérateur de communauté",
     "Discord / Slack bot flagging spam, scams and toxicity with probabilities, escalating edge cases.",
     "Bot Discord / Slack qui signale spam, arnaques et toxicité avec probabilités, et escalade les cas limites.",
     "Community managers", "Community managers", "$19/server/mo"),
    ("review_mod", "moderation", "Marketplace review screener", "Filtrage d'avis clients",
     "Detects fake, off-topic or abusive reviews on marketplaces and apps.",
     "Détecte les avis faux, hors sujet ou abusifs sur les marketplaces et les apps.",
     "Marketplaces", "Marketplaces", "usage-based"),
    ("site_search", "search_ranking", "Intent reranker for site search", "Reranker d'intention pour recherche",
     "Plug-in reranker that makes Shopify or docs search understand what people mean.",
     "Reranker à brancher qui fait comprendre à la recherche Shopify ou d'une doc ce que les gens veulent dire.",
     "E-commerce, docs sites", "E-commerce, sites de doc", "$29/mo"),
    ("rag_filter", "search_ranking", "RAG passage gatekeeper", "Filtre de passages RAG",
     "Scores retrieved passages, drops irrelevant or injected ones before they reach the LLM.",
     "Note les passages récupérés et écarte les non pertinents ou piégés avant qu'ils n'atteignent le LLM.",
     "AI app builders", "Créateurs d'apps IA", "usage-based"),
    ("adaptive_landing", "adaptive_ui", "Adaptive landing pages", "Landing pages adaptatives",
     "Reorders sections and CTAs per visitor from their referrer and behavior, in real time.",
     "Réorganise sections et CTA pour chaque visiteur selon sa provenance et son comportement, en temps réel.",
     "SaaS marketers", "Marketeurs SaaS", "$49/mo"),
    ("predictive_launcher", "adaptive_ui", "Predictive launcher", "Lanceur prédictif",
     "Spotlight-style launcher that understands 'the pdf I just downloaded'.",
     "Lanceur type Spotlight qui comprend « le pdf que je viens de télécharger ».",
     "Mac power users", "Utilisateurs Mac avancés", "$5/mo"),
    ("npc_sdk", "game_bots", "Reactive NPC SDK", "SDK de PNJ réactifs",
     "Unity / Godot plugin giving NPCs fast decisions at 10 Hz for pennies per hour of play.",
     "Plugin Unity / Godot qui donne aux PNJ des décisions rapides à 10 Hz pour quelques centimes par heure de jeu.",
     "Indie game devs", "Devs de jeux indés", "per-game license"),
    ("game_qa", "game_bots", "Game playtesting bots", "Bots de playtest",
     "Hundreds of Jev-driven players that find exploits and soft-locks before launch.",
     "Des centaines de joueurs pilotés par Jev qui trouvent exploits et blocages avant la sortie.",
     "Game studios", "Studios de jeu", "$199/mo"),
    ("trade_filter", "trading_signals", "Signal sanity filter", "Filtre de signaux de trading",
     "Scores news and signals for relevance and risk before a strategy acts (not financial advice).",
     "Note l'actualité et les signaux (pertinence, risque) avant qu'une stratégie n'agisse (pas un conseil financier).",
     "Algo traders", "Traders algorithmiques", "$29/mo"),
    ("drone_brain", "robotics_iot", "Decision layer for hobby robots", "Couche de décision pour robots",
     "ROS / Raspberry Pi package turning sensor state into fast typed decisions.",
     "Package ROS / Raspberry Pi qui transforme l'état des capteurs en décisions typées rapides.",
     "Makers, robotics labs", "Makers, labos de robotique", "license"),
    ("jev_zapier", "dev_integration", "Jev for Zapier / n8n / Make", "Jev pour Zapier / n8n / Make",
     "No-code 'Decide' step: classify, score or route anything inside automations.",
     "Étape no-code « Décider » : classer, noter ou aiguiller n'importe quoi dans les automatisations.",
     "No-code builders", "Créateurs no-code", "marketplace"),
    ("jev_mcp", "dev_integration", "Jev MCP server", "Serveur MCP Jev",
     "MCP server exposing typed decisions to any agent, with caching and cost dashboards.",
     "Serveur MCP qui expose des décisions typées à n'importe quel agent, avec cache et suivi des coûts.",
     "Agent developers", "Développeurs d'agents", "$9/mo"),
    ("jev_course", "education_content", "Build-with-Jev course", "Formation « construire avec Jev »",
     "Templates and lessons for the 10 most profitable Jev patterns.",
     "Templates et leçons pour les 10 patterns Jev les plus rentables.",
     "Developers", "Développeurs", "$49 one-off"),
    ("resume_screen", None, "Resume & application screener", "Tri de candidatures",
     "Scores applications against a role's must-haves with explainable typed checks.",
     "Note chaque candidature selon les critères indispensables du poste, avec des contrôles typés explicables.",
     "Recruiters, SMBs", "Recruteurs, PME", "$49/mo"),
    ("contract_flags", None, "Contract clause flagger", "Détecteur de clauses de contrat",
     "Flags risky clauses (auto-renewal, liability, IP) in contracts in seconds.",
     "Repère en quelques secondes les clauses risquées (reconduction, responsabilité, PI) dans les contrats.",
     "Freelancers, SMBs", "Freelances, PME", "$19/mo"),
    ("invoice_triage", None, "Invoice & receipt categorizer", "Catégorisation de factures",
     "Categorizes receipts and invoices for bookkeeping and flags anomalies.",
     "Catégorise reçus et factures pour la compta et signale les anomalies.",
     "Accountants, freelancers", "Comptables, freelances", "$15/mo"),
    ("listing_quality", None, "Marketplace listing optimizer", "Optimiseur d'annonces",
     "Scores Etsy / Amazon / Airbnb listings on the factors that drive conversion.",
     "Note les annonces Etsy / Amazon / Airbnb sur les facteurs qui font convertir.",
     "Sellers, hosts", "Vendeurs, hôtes", "$15/mo"),
    ("product_taxonomy", None, "Product catalog categorizer", "Catégorisation de catalogue",
     "Maps thousands of SKUs into a taxonomy with confidence, sends doubtful ones to a human.",
     "Range des milliers de références dans une taxonomie avec un niveau de confiance, envoie les cas douteux à un humain.",
     "E-commerce ops", "Ops e-commerce", "usage-based"),
    ("real_estate_match", None, "Property-buyer matcher", "Matching biens-acheteurs",
     "Scores listings against each buyer's written wishes and alerts on strong matches.",
     "Note les annonces selon les souhaits écrits de chaque acheteur et alerte sur les meilleures correspondances.",
     "Real estate agents", "Agents immobiliers", "$39/mo"),
    ("job_alerts", None, "Smart job alerts", "Alertes emploi intelligentes",
     "Reads every new job post and keeps only the ones that truly match a candidate.",
     "Lit chaque nouvelle offre d'emploi et ne garde que celles qui correspondent vraiment au candidat.",
     "Job seekers", "Chercheurs d'emploi", "$7/mo"),
    ("grant_finder", None, "Grant & tender matcher", "Matching d'appels d'offres",
     "Scans public tenders and grants daily and ranks them for each company.",
     "Parcourt chaque jour les appels d'offres et subventions publics et les classe pour chaque entreprise.",
     "SMBs, consultancies", "PME, cabinets", "$59/mo"),
    ("med_intake", None, "Clinic message triage", "Tri des messages de cabinet médical",
     "Routes patient messages by urgency and type for small clinics (human in the loop).",
     "Aiguille les messages patients par urgence et par type pour les petits cabinets (avec validation humaine).",
     "Clinics", "Cabinets", "$79/mo"),
    ("edu_grader", None, "Quiz & short-answer grader", "Correction de réponses courtes",
     "Grades short answers against rubrics instantly with confidence, flags borderline cases.",
     "Corrige instantanément les réponses courtes selon une grille, avec confiance, et signale les cas limites.",
     "Teachers, course creators", "Enseignants, formateurs", "$9/mo"),
    ("review_insights", None, "Review insights for apps", "Analyse des avis d'apps",
     "Turns App Store and Play reviews into typed issues, trends and priorities.",
     "Transforme les avis App Store et Play en problèmes typés, tendances et priorités.",
     "Mobile teams", "Équipes mobile", "$29/mo"),
    ("seo_intent", None, "Search-intent keyword sorter", "Tri de mots-clés par intention",
     "Labels thousands of keywords by intent, funnel stage and topic cluster.",
     "Classe des milliers de mots-clés par intention, étape du funnel et cluster thématique.",
     "SEO agencies", "Agences SEO", "$29/mo"),
    ("compliance_screen", None, "Marketing compliance screener", "Contrôle de conformité marketing",
     "Checks ads and emails for risky claims (health, finance) before they ship.",
     "Vérifie pubs et emails pour repérer les affirmations risquées (santé, finance) avant envoi.",
     "Regulated brands", "Marques réglementées", "$99/mo"),
    ("phishing_guard", None, "Phishing & scam email guard", "Protection anti-phishing",
     "Scores each email and link for scam likelihood for small teams without a SOC.",
     "Note la probabilité d'arnaque de chaque email et lien, pour les petites équipes sans SOC.",
     "Small businesses", "Petites entreprises", "$4/user/mo"),
    ("meeting_actions", None, "Meeting follow-up router", "Routeur de suites de réunion",
     "Classifies transcript segments into decisions, tasks and owners, pushes them to tools.",
     "Classe les passages d'une transcription en décisions, tâches et responsables, et les pousse dans les outils.",
     "Remote teams", "Équipes à distance", "$8/seat/mo"),
    ("doc_router", None, "Document intake router", "Aiguillage de documents",
     "Sorts incoming PDFs (IDs, invoices, contracts, forms) and routes each to the right workflow.",
     "Trie les PDF entrants (pièces d'identité, factures, contrats, formulaires) et envoie chacun vers le bon workflow.",
     "Back offices", "Back-offices", "usage-based"),
]

IDEAS = [dict(zip(("k", "n", "en", "fr", "pen", "pfr", "ben", "bfr", "price"), row)) for row in _IDEAS]

CRITERIA = {
    "pain": ["Nice to have, nobody pays for this today", "Mild annoyance", "Real recurring pain",
             "Costly problem teams already spend money on", "Critical problem with an obvious budget"],
    "recurring": ["One-off purchase at best", "Occasional use", "Monthly use is plausible",
                  "Used every week, subscription feels natural", "Used every day, usage-based billing grows by itself"],
    "automation": ["Needs the owner's constant manual work", "Frequent manual intervention",
                   "Some support and tuning", "Mostly runs by itself", "Fully self-serve, runs unattended"],
    "jev_fit": ["Needs long text generation, Jev does not help", "Jev helps marginally",
                "Jev handles an important part", "The core is fast typed decisions, ideal for Jev",
                "Impossible or uneconomic without Jev's speed and price"],
    "open_market": ["Crowded with strong incumbents", "Several good competitors", "Some competition",
                    "Few serious competitors", "Wide open"],
    "build_ease": ["Needs a large team and months", "Hard for a solo developer", "A few weeks for a solo developer",
                   "An MVP in about a week", "An MVP in a weekend"],
}
QUESTIONS_TEXT = {
    "pain": "How painful and costly is the problem this product solves for its buyer?",
    "recurring": "How naturally does this product generate recurring revenue?",
    "automation": "Once built, how much can this product run without its owner's ongoing work?",
    "jev_fit": "How much does this product's core rely on fast, cheap, typed decisions (Jev's strength) rather than generated text?",
    "open_market": "How open is the market for this product today?",
    "build_ease": "How easy is it for a solo developer to ship a first version?",
}
IDEA_WEIGHTS = {"pain": 0.2, "recurring": 0.2, "automation": 0.2, "jev_fit": 0.15, "open_market": 0.1, "build_ease": 0.05, "x_signal": 0.1}
